#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_訂單專題
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mid_proj")]
	public partial class mid_proj_DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertOrders(Orders instance);
    partial void UpdateOrders(Orders instance);
    partial void DeleteOrders(Orders instance);
    partial void Insertorder_detail(order_detail instance);
    partial void Updateorder_detail(order_detail instance);
    partial void Deleteorder_detail(order_detail instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    #endregion
		
		public mid_proj_DataClasses1DataContext() : 
				base(global::WindowsFormsApp_訂單專題.Properties.Settings.Default.mid_projConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public mid_proj_DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mid_proj_DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mid_proj_DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mid_proj_DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Orders> Orders
		{
			get
			{
				return this.GetTable<Orders>();
			}
		}
		
		public System.Data.Linq.Table<order_detail> order_detail
		{
			get
			{
				return this.GetTable<order_detail>();
			}
		}
		
		public System.Data.Linq.Table<Product> Product
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
	public partial class Orders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _O_ID;
		
		private System.DateTime _O_datetime;
		
		private string _INorOUT;
		
		private string _Tel;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnO_IDChanging(string value);
    partial void OnO_IDChanged();
    partial void OnO_datetimeChanging(System.DateTime value);
    partial void OnO_datetimeChanged();
    partial void OnINorOUTChanging(string value);
    partial void OnINorOUTChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    #endregion
		
		public Orders()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_ID", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string O_ID
		{
			get
			{
				return this._O_ID;
			}
			set
			{
				if ((this._O_ID != value))
				{
					this.OnO_IDChanging(value);
					this.SendPropertyChanging();
					this._O_ID = value;
					this.SendPropertyChanged("O_ID");
					this.OnO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_datetime", DbType="DateTime NOT NULL")]
		public System.DateTime O_datetime
		{
			get
			{
				return this._O_datetime;
			}
			set
			{
				if ((this._O_datetime != value))
				{
					this.OnO_datetimeChanging(value);
					this.SendPropertyChanging();
					this._O_datetime = value;
					this.SendPropertyChanged("O_datetime");
					this.OnO_datetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INorOUT", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string INorOUT
		{
			get
			{
				return this._INorOUT;
			}
			set
			{
				if ((this._INorOUT != value))
				{
					this.OnINorOUTChanging(value);
					this.SendPropertyChanging();
					this._INorOUT = value;
					this.SendPropertyChanged("INorOUT");
					this.OnINorOUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_detail")]
	public partial class order_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _O_ID;
		
		private short _No;
		
		private string _main;
		
		private System.Nullable<short> _qty_main;
		
		private System.Nullable<bool> _is_mealset;
		
		private string _beverage;
		
		private System.Nullable<short> _qty_beverage;
		
		private string _sweet;
		
		private System.Nullable<short> _qty_sweet;
		
		private System.Nullable<int> _total;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnO_IDChanging(string value);
    partial void OnO_IDChanged();
    partial void OnNoChanging(short value);
    partial void OnNoChanged();
    partial void OnmainChanging(string value);
    partial void OnmainChanged();
    partial void Onqty_mainChanging(System.Nullable<short> value);
    partial void Onqty_mainChanged();
    partial void Onis_mealsetChanging(System.Nullable<bool> value);
    partial void Onis_mealsetChanged();
    partial void OnbeverageChanging(string value);
    partial void OnbeverageChanged();
    partial void Onqty_beverageChanging(System.Nullable<short> value);
    partial void Onqty_beverageChanged();
    partial void OnsweetChanging(string value);
    partial void OnsweetChanged();
    partial void Onqty_sweetChanging(System.Nullable<short> value);
    partial void Onqty_sweetChanged();
    partial void OntotalChanging(System.Nullable<int> value);
    partial void OntotalChanged();
    #endregion
		
		public order_detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O_ID", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string O_ID
		{
			get
			{
				return this._O_ID;
			}
			set
			{
				if ((this._O_ID != value))
				{
					this.OnO_IDChanging(value);
					this.SendPropertyChanging();
					this._O_ID = value;
					this.SendPropertyChanged("O_ID");
					this.OnO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short No
		{
			get
			{
				return this._No;
			}
			set
			{
				if ((this._No != value))
				{
					this.OnNoChanging(value);
					this.SendPropertyChanging();
					this._No = value;
					this.SendPropertyChanged("No");
					this.OnNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_main", DbType="NVarChar(50)")]
		public string main
		{
			get
			{
				return this._main;
			}
			set
			{
				if ((this._main != value))
				{
					this.OnmainChanging(value);
					this.SendPropertyChanging();
					this._main = value;
					this.SendPropertyChanged("main");
					this.OnmainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty_main", DbType="SmallInt")]
		public System.Nullable<short> qty_main
		{
			get
			{
				return this._qty_main;
			}
			set
			{
				if ((this._qty_main != value))
				{
					this.Onqty_mainChanging(value);
					this.SendPropertyChanging();
					this._qty_main = value;
					this.SendPropertyChanged("qty_main");
					this.Onqty_mainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_mealset", DbType="Bit")]
		public System.Nullable<bool> is_mealset
		{
			get
			{
				return this._is_mealset;
			}
			set
			{
				if ((this._is_mealset != value))
				{
					this.Onis_mealsetChanging(value);
					this.SendPropertyChanging();
					this._is_mealset = value;
					this.SendPropertyChanged("is_mealset");
					this.Onis_mealsetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beverage", DbType="NVarChar(50)")]
		public string beverage
		{
			get
			{
				return this._beverage;
			}
			set
			{
				if ((this._beverage != value))
				{
					this.OnbeverageChanging(value);
					this.SendPropertyChanging();
					this._beverage = value;
					this.SendPropertyChanged("beverage");
					this.OnbeverageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty_beverage", DbType="SmallInt")]
		public System.Nullable<short> qty_beverage
		{
			get
			{
				return this._qty_beverage;
			}
			set
			{
				if ((this._qty_beverage != value))
				{
					this.Onqty_beverageChanging(value);
					this.SendPropertyChanging();
					this._qty_beverage = value;
					this.SendPropertyChanged("qty_beverage");
					this.Onqty_beverageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sweet", DbType="NVarChar(50)")]
		public string sweet
		{
			get
			{
				return this._sweet;
			}
			set
			{
				if ((this._sweet != value))
				{
					this.OnsweetChanging(value);
					this.SendPropertyChanging();
					this._sweet = value;
					this.SendPropertyChanged("sweet");
					this.OnsweetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty_sweet", DbType="SmallInt")]
		public System.Nullable<short> qty_sweet
		{
			get
			{
				return this._qty_sweet;
			}
			set
			{
				if ((this._qty_sweet != value))
				{
					this.Onqty_sweetChanging(value);
					this.SendPropertyChanging();
					this._qty_sweet = value;
					this.SendPropertyChanged("qty_sweet");
					this.Onqty_sweetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _P_ID;
		
		private string _P_Name;
		
		private string _P_type;
		
		private int _P_price;
		
		private string _P_image;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_IDChanging(int value);
    partial void OnP_IDChanged();
    partial void OnP_NameChanging(string value);
    partial void OnP_NameChanged();
    partial void OnP_typeChanging(string value);
    partial void OnP_typeChanged();
    partial void OnP_priceChanging(int value);
    partial void OnP_priceChanged();
    partial void OnP_imageChanging(string value);
    partial void OnP_imageChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int P_ID
		{
			get
			{
				return this._P_ID;
			}
			set
			{
				if ((this._P_ID != value))
				{
					this.OnP_IDChanging(value);
					this.SendPropertyChanging();
					this._P_ID = value;
					this.SendPropertyChanged("P_ID");
					this.OnP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Name
		{
			get
			{
				return this._P_Name;
			}
			set
			{
				if ((this._P_Name != value))
				{
					this.OnP_NameChanging(value);
					this.SendPropertyChanging();
					this._P_Name = value;
					this.SendPropertyChanged("P_Name");
					this.OnP_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string P_type
		{
			get
			{
				return this._P_type;
			}
			set
			{
				if ((this._P_type != value))
				{
					this.OnP_typeChanging(value);
					this.SendPropertyChanging();
					this._P_type = value;
					this.SendPropertyChanged("P_type");
					this.OnP_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_price", DbType="Int NOT NULL")]
		public int P_price
		{
			get
			{
				return this._P_price;
			}
			set
			{
				if ((this._P_price != value))
				{
					this.OnP_priceChanging(value);
					this.SendPropertyChanging();
					this._P_price = value;
					this.SendPropertyChanged("P_price");
					this.OnP_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_image", DbType="NVarChar(50)")]
		public string P_image
		{
			get
			{
				return this._P_image;
			}
			set
			{
				if ((this._P_image != value))
				{
					this.OnP_imageChanging(value);
					this.SendPropertyChanging();
					this._P_image = value;
					this.SendPropertyChanged("P_image");
					this.OnP_imageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
